version: 0.0
os: linux
files:
    - source: /
      destination: /home/sha.ni.webproject
permission:
    - object: /home/sha.ni.webproject
hooks:
    AfterInstall:
    - location: scripts/stop_and_remove_images.sh
      runas: root
    - location: scripts/build_image.sh
      runas: root
    - location: scripts/start_server.sh
      runas: root
